apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: goodacr.azurecr.io/kwujio/front:latest
