apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: front
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: http
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: goodbirdacr.azurecr.io/medicine/front:latest
          resources:
            requests:
              cpu: 10m
              memory: 50Mi     
            limits:
              cpu: 100m
              memory: 50Mi
          ports: 
            - containerPort: 80
        - name: metrics
          image: nginx/nginx-prometheus-exporter
          resources:
            requests:
              cpu: 10m
              memory: 50Mi     
            limits:
              cpu: 100m
              memory: 50Mi
          ports: 
            - containerPort: 9113
      imagePullSecrets:
        - name: goodbirdacr


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-end-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 11



