apiVersion: apps/v1
kind: Deployment
metadata:

  name: front-end-deployment
  namespace: front
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: http
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: goodbirdacr.azurecr.io/medicine/front:latest
      - name: metrics
        image: docker.io/bitnami/nginx-exporter:1.1.0-debian-11-r3
        ports: 
          - containerPort: 9113
            name: metrics
            protocol: TCP
        args:
          - --nginx.scrape-uri
          - http://127.0.0.1:8080/status
          - --web.listen-address
          - :9113
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
            scheme: HTTP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: metrics
            scheme: HTTP
