apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goodacr.azurecr.io/kwujio/front
  newName: goodacr.azurecr.io/kwujio/front
  newTag: latest