apiVersion: v1
kind: Service

metadata:
  name: front-end-service
  namespace: front
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
  type: NodePort
